### ISSUE TITLE
Программа не возвращает ошибку, если игра не была установлена

### ISSUE THREAD

**Issue by MarinaMatvienko** [MarinaMatvienko/TeamWork#10]
# Описание
Vетод play должен выкидывать исключение RuntimeException, а он падает и выдает: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.
 
# Локализация дефекта
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/Player.java#L28-L41

# Шаги воспроизведения

Шаги воспроизведения:
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork) в IDEA.
2. Запустить тест [shouldThrowExceptionWhenGameNotInstalled](https://github.com/MarinaMatvienko/TeamWork/main/src/test/java/PlayerTest.java) класса PlayerTest.

Ожидаемый результат: Тест shouldThrowExceptionWhenGameNotInstalled проходит успешно. В логе отсутствуют ошибки

Фактический результат: Тест shouldThrowExceptionWhenGameNotInstalled падает с ошибкой:
org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
![image](https://user-images.githubusercontent.com/111412093/213307254-6580e8fb-9996-476c-9368-15cbbfc4be54.png)

# Окружение
* **Операционная система:**Выпуск	Windows 10 Домашняя для одного языка. Версия	21H1. Сборка ОС	19043.2130
* **IDE:** intelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by OlgaBrazh** [comment]
Метод play класса Player исправлен.
