### ISSUE TITLE
Метод sumGenre класса Player не суммирует количество часов, которые играл игрок в заданном жанре, если добавлены игры разных жанров.

### ISSUE THREAD

**Issue by MarinaMatvienko** [MarinaMatvienko/TeamWork#11]
# Описание
Тест метода sumGenre падает, не суммирует количество часов, которые играл игрок в заданном жанре.
Добавлено несколько игр разных жанров.
 
# Локализация дефекта
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/Player.java#L43-L55

# Шаги воспроизведения

Шаги воспроизведения:
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork) в IDEA.
2. Запустить тест [sumGenreTwoGames](https://github.com/MarinaMatvienko/TeamWork/main/src/test/java/PlayerTest.java) класса PlayerTest.

Ожидаемый результат: Тест sumGenreTwoGames проходит успешно.

Фактический результат: Тест sumGenreTwoGames падает с ошибкой:
org.opentest4j.AssertionFailedError:
Expected :7
Actual :0

# Скриншот
![image](https://user-images.githubusercontent.com/111412093/213311332-c21e0e67-c92f-47b8-a187-e04b6f054252.png)

# Окружение
* **Операционная система:**Выпуск	Windows 10 Домашняя для одного языка. Версия	21H1. Сборка ОС	19043.2130
* **IDE:** intelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by OlgaBrazh** [comment]
Метод sumGenre класса Player исправлен
