### ISSUE TITLE
Метод mostPlayerByGenre в классе Player выдает ответ null вместо названия игры, в которую больше всего играли в выбраном жанре, если игры разных жанров

### ISSUE THREAD

**Issue by MarinaMatvienko** [MarinaMatvienko/TeamWork#12]
# Описание
Тест метода mostPlayerByGenre, который должен определять игру заданного жанра, в которую играли больше всего, падает.

 
# Локализация дефекта
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/Player.java#L57-L62

# Шаги воспроизведения

Шаги воспроизведения:
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork) в IDEA.
2. Запустить тест [shouldReturnMostPlayedByGenreWhenSomeGamesDifferentGenres](https://github.com/MarinaMatvienko/TeamWork/main/src/test/java/PlayerTest.java) класса PlayerTest.

Ожидаемый результат: Тест shouldReturnMostPlayedByGenreWhenSomeGamesDifferentGenres проходит успешно. 

Фактический результат: shouldReturnMostPlayedByGenreWhenSomeGamesDifferentGenres падает с ошибкой:
org.opentest4j.AssertionFailedError:
Expected :Идиот
Actual :null

# Скриншот
![image](https://user-images.githubusercontent.com/111412093/213311042-30634b5b-e0c9-46a8-8afd-e3d17326f279.png)

# Окружение
* **Операционная система:**Выпуск	Windows 10 Домашняя для одного языка. Версия	21H1. Сборка ОС	19043.2130
* **IDE:** intelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by OlgaBrazh** [comment]
Метод mostPlayerByGenre класса Player исправлен
