### ISSUE TITLE
Метод sumGenre класса Player возвращает ноль вместо количества часов

### ISSUE THREAD

**Issue by MarinaMatvienko** [MarinaMatvienko/TeamWork#2]
# Описание
Тест метода sumGenre, подсчет суммарного времени в одном жанре заданным игроком, падает.
 
# Локализация дефекта
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения

Шаги воспроизведения:
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork) в IDEA.
2. Запустить [тест shouldSumGenreIfOneGame](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/test/java/PlayerTest.java#L9-L20) класса PlayerTest.

Посмотреть ответ в консоли.

**Ожидаемый результат:** Успешно прошел тест.
**Фактический результат:** Тест падает с ошибкой:
_org.opentest4j.AssertionFailedError:_
Expected: 3
Actual: 0

# Скриншот
![image](https://user-images.githubusercontent.com/111412093/212467189-f07fc200-8373-4fb6-a216-1d91bef8d45f.png)

# Окружение
* **Операционная система:**Выпуск	Windows 10 Домашняя для одного языка. Версия	21H1. Сборка ОС	19043.2130
* **IDE:** intelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by OlgaBrazh** [comment]
Метод sumGenre класса Player исправлен
