### ISSUE TITLE
Метод containsGame возвращает false вместо true, если игра в каталоге есть.

### ISSUE THREAD

**Issue by OlgaBrazh** [MarinaMatvienko/TeamWork#3]
# Описание
Метод containsGame в классе GameStore возвращает false вместо true, если игра в каталоге есть. Тест метода не проходит.

# Локация дефекта
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/test/java/GameStoreTest.java#L8-L16

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA.
2. Запустить в классе GameStoreTest [тест shouldAddGame](https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/test/java/GameStoreTest.java#L8-L16).
3. Посмотреть результат теста в консоли.

*Ожидаемый результат:* тест пройден. 
*Фактический результат:* тест падает. Ошибка
org.opentest4j.AssertionFailedError: 
*Expected :* true
*Actual   :* false

# Скриншот
![image](https://user-images.githubusercontent.com/102176272/212481529-a81c81cc-782d-4340-8e4a-36b52dea0471.png)

# Окружение:
Операционная система: Ubuntu 18.04.6 LTS
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by MarinaMatvienko** [comment]
Исправлен Метод containsGame.
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/GameStore.java#L33-L34
