### ISSUE TITLE
Метод addPlayTime класса GameStore не суммирует время игрока за игрой каталога.

### ISSUE THREAD

**Issue by OlgaBrazh** [MarinaMatvienko/TeamWork#4]
# Описание
Метод addPlayTime класса GameStore, если условие в if выполняется, не суммирует время игрока за игрой каталога с прошлым значением для этого игрока. Тест метода падает.

# Локация дефекта
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA.
2. В классе GameStoreTest запустить тест [shouldAddPlayTimeIfMapContainsKey](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/test/java/GameStoreTest.java).
3. Посмотреть результат в консоли.

*Ожидаемый результат:* тест пройден. 
*Фактический результат:* тест не пройден. Ошибка
org.opentest4j.AssertionFailedError: 
*Expected :* 5
*Actual   :* 1

# Скриншот
![image](https://user-images.githubusercontent.com/102176272/212483467-75de2fe9-6352-4655-b02c-1ab94cde15e9.png)

# Окружение
* **Операционная система:** Ubuntu 18.04.6 LTS
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by MarinaMatvienko** [comment]
[Исправлен метод addPlayTime](https://github.com/MarinaMatvienko/TeamWork/commit/055e7b2092658798a5c7effb48ec680eb9dd87b4)
