### ISSUE TITLE
Метод getMostPlayer класса GameStore возвращает null вместо имени игрока с самым большим временем игры

### ISSUE THREAD

**Issue by OlgaBrazh** [MarinaMatvienko/TeamWork#6]
# Описание
Метод getMostPlayer класса GameStore возвращает null вместо имени игрока, который играл в игры этого каталога больше всего, когда такой игрок есть (null метод должен возвращать, только если такого игрока нет). Тест метода падает.

# Локация дефекта 
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/GameStore.java#L58-L69

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA.
2. В классе GameStoreTest запустить тест [shouldFindBestPlayer](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/test/java/GameStoreTest.java).
3. Посмотреть результат в консоли.

*Ожидаемый результат:* тест пройден. 
*Фактический результат:* тест не пройден. Ошибка

org.opentest4j.AssertionFailedError: 
*Expected :* Marina
*Actual :* null

# Скриншот
![image](https://user-images.githubusercontent.com/102176272/212866942-77e53bc3-b125-4915-bce0-2d8ee610eab3.png)

# Окружение
* **Операционная система:** Ubuntu 18.04.6 LTS
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by MarinaMatvienko** [comment]
[Исправлен метод getMostPlayer](https://github.com/MarinaMatvienko/TeamWork/commit/f2fb2947ddb1fe0e4e27a9b97682d1ce3ed8409e)
