### ISSUE TITLE
Метод getSumPlayedTime возвращает ноль вместо суммарного количества времени игроков за игрой каталога 

### ISSUE THREAD

**Issue by OlgaBrazh** [MarinaMatvienko/TeamWork#7]
# Описание
Метод getSumPlayedTime класса GameStore возвращает ноль при подсчете общего количества времени всех игроков за игрой каталог. Метод не описан полностью. Тест метода падает.

# Локация дефекта 
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA.
2. В классе GameStoreTest запустить тест [shouldgetSumPlayedTime](https://github.com/MarinaMatvienko/TeamWork/blob/main/src/test/java/GameStoreTest.java).
3. Посмотреть результат в консоли.

*Ожидаемый результат:* тест пройден. 
*Фактический результат:* тест не пройден. Ошибка

org.opentest4j.AssertionFailedError: 
*Expected :* 25
*Actual   :* 0

# Скриншот
![image](https://user-images.githubusercontent.com/102176272/212872460-a2890971-5f11-41a3-aa5f-f5dd83d59ee5.png)

# Окружение
* **Операционная система:** Ubuntu 18.04.6 LTS
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by MarinaMatvienko** [comment]
Исправлен метод getSumPlayedTime. https://github.com/MarinaMatvienko/TeamWork/blob/a693576fe2ae4a5a7ffa8b9a939b6b06461e36cd/src/main/java/ru/netology/GameStore.java#L75-L80
