### ISSUE TITLE
Метод sumGenre класса Player не суммирует количество часов, которые играл игрок в заданном жанре, если добавляют игры только одного жанра.

### ISSUE THREAD

**Issue by MarinaMatvienko** [MarinaMatvienko/TeamWork#9]
# Описание
Тест метода sumGenre, подсчет суммарного времени игры в игры одного жанра заданным игроком падает.
Добавлено несколько игр одного жанра.
 
# Локализация дефекта
https://github.com/MarinaMatvienko/TeamWork/blob/f763286460f5eb749d75e9c2760ff392e249886c/src/main/java/ru/netology/Player.java#L43-L55

# Шаги воспроизведения

Шаги воспроизведения:
1. Открыть [код программы](https://github.com/MarinaMatvienko/TeamWork) в IDEA.
2. Запустить тест [shouldSumGenreIfSomeGame](https://github.com/MarinaMatvienko/TeamWork/main/src/test/java/PlayerTest.java) класса PlayerTest.

Ожидаемый результат: Тест shouldSumGenreIfSomeGame прошел успешно.

Фактический результат: Тест shouldSumGenreIfSomeGame падает с ошибкой:
org.opentest4j.AssertionFailedError:
Expected :21
Actual :0

# Скриншот
![image](https://user-images.githubusercontent.com/111412093/213311551-02d0774d-2397-4f88-ad77-3d1f8e4738fb.png)

# Окружение
* **Операционная система:**Выпуск	Windows 10 Домашняя для одного языка. Версия	21H1. Сборка ОС	19043.2130
* **IDE:** intelliJ IDEA 2022.2.3 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by OlgaBrazh** [comment]
Метод sumGenre класса Player исправлен
